[package]
name = "ftdata-sources"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
chrono.workspace = true
tracing.workspace = true
async-trait.workspace = true
url.workspace = true
once_cell.workspace = true

ftdata-core = { path = "../ftdata-core" }
ftdata-http = { path = "../ftdata-http" }
