[package]
name = "ftdata-http"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
reqwest.workspace = true
http = "1.1"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true
parking_lot.workspace = true
futures.workspace = true
tokio-util.workspace = true
url.workspace = true
