[package]
name = "ftdata-analysis"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
chrono.workspace = true
tracing.workspace = true
polars.workspace = true

ftdata-core = { path = "../ftdata-core" }
ftdata-storage = { path = "../ftdata-storage" }
